### ISSUE TITLE
Idiomatic way to support Function Call tags

### ISSUE THREAD

**Issue by farzadshafiee** [idehub/react-native-google-analytics-bridge#255] opened 2018-06-12 16:18 UTC
I want to leverage [Function Call](https://developers.google.com/tag-manager/ios/v3/#function-call-tag) to streamline a few of our integrations and eliminate app update cylce with every configuration change. This is a powerful feature of GTM can be applied for many use-cases.

Now, I was looking into the possibility of registering functions in JS realm, but based on the Google documentations, the function must be registered in native realm. I am not very experienced with writing native apps, but here's my idea which I think can be used to extend APIs of this module:

In native realm, a single function call handler is registed on the Tag Manager container when it's opened. Let's call it `functionCallTagHandler`. This clas

**Comment by cbrevik** [comment] 2018-06-12 18:03
Duplicate of #256

**Closed by cbrevik** 2018-06-12 18:03 UTC
Labels: duplicate
