### ISSUE TITLE
Required dispatch_sync...may lead to deadlocks

### ISSUE THREAD

**Issue by mcnamee** [idehub/react-native-google-analytics-bridge#70] opened 2016-10-07 00:48 UTC
Hi,
I'm getting a YellowBox with the following warning:

`Required dispatch_sync to load constants for RCTGoogleAnalyticsBridge. This may lead to deadlocks`

And if this helps, this is a raw log in XCode:

`[warn][tid:com.facebook.react.RCTBridgeQueue][RCTModuleData.mm:220] RCTBridge required dispatch_sync to load RCTGoogleAnalyticsBridge. This may lead to deadlocks`

Any tips on where to look to solve?

**Comment by cbrevik** [comment] 2016-10-08 08:29
Hi @mcnamee,

When do you get this error? Also which RN version are you running?

**Comment by mcnamee** [comment] 2016-10-08 08:36
Hey, it happens as soon as the app starts up and using RN0.34. 

https://github.com/mcnamee/react-native-starter-app

**Comment by cbrevik** [comment] 2016-10-08 09:43
Hey, thanks for the code example. I ran the app but don't seem to be able to reproduce the problem.

I have been getting the same yellow box intermittently with CodePush in another app I am building, so it isn't completely unfamiliar to me. 

Do you get the error every time you start the app?

**Comment by mcnamee** [comment] 2016-10-08 11:46
The log in Xcode (not remote debug) does happen every time I refresh the app - although it infrequently/randomly shows the YellowBox when refreshing.

**Comment by cbrevik** [comment] 2016-10-08 12:17
Hm, I got it for `RCTUIManager` first, but now I get it consistently for `RCTGoogleAnalyticsBridge`:

```
[tid:com.facebook.react.RCTBridgeQueue][RCTModuleData.mm:287] Required dispatch_sync to load constants for RCTGoogleAnalyticsBridge. This may lead to deadlocks
```

It seems to be related to the framework [loading the constants from native modules in `gatherConstants`](https://github.com/facebook/react-native/blob/cfae3e376d96653e5ad48e0d0398674a954d3637/React/Base/RCTModuleData.mm#L287). That method is used in [RCTBatchedBridge](https://github.com/facebook/react-native/blob/9981b8928d20416d1a3f3995b9f4d32ccf273ebd/React/Base/RCTBatchedBridge.m#L419), which as the following comment:
>    // Modules that need to be set up on the main thread cannot be initialized
      // lazily when required without doing a dispatch_sync to the main thread,
      // which can result in deadlock. To avoid this, we initialize all of these
      // modules on the main thread in parallel with loading the JS code, so
      // they will already be available before they are ever required.

The warning (+ check) seems to have been introduced in [this commit](https://github.com/facebook/react-native/commit/0222107170a32b9f60929ae0b2096e4bc4f215df) which was included in RN 0.33+.

**Comment by cbrevik** [comment] 2016-10-13 08:09
Seems like the answer from the above referenced issue is that this is a non-critical warning. I've been unable to find out if there is something differently with exporting constants, but it shouldn't be a problem. 

Closing the issue since it doesn't seem to be something that is unique to this module.

**Closed by cbrevik** 2016-10-13 08:09 UTC

**Comment by smooJitter** [comment] 2016-12-20 05:00
@mcnamee I'm getting the same problem with the same app.  I'm interested in hearing how you got around it.

**Comment by mcnamee** [comment] 2016-12-20 08:20
Hey @smooJitter - it doesn't look to be a concern that causes any harm - just a warning.
Apparently a known issue with the core RNBridge initialisation.

We've been ignoring it and it hasn't caused any issues with production apps.

**Comment by connected-tlip** [comment] 2017-01-25 20:59
Our app hangs when debugging when we export constants from an iOS module.

**Comment by ds300** [comment] 2017-03-10 13:35
@connected-tlip did you find a way around this? My app also hangs when debugging, and I'm getting this warning just before the hang.

**Comment by amanthegreatone** [comment] 2017-05-30 14:29
having the above issue like @ds300

**Comment by ababba15** [comment] 2017-06-10 14:46
X-Code makes breakpoints. Seems like that's a little more than non-critical warning..

**Comment by vaenx** [comment] 2018-05-01 12:10
I keep having this warning. Has someone found a solution?
