### ISSUE TITLE
Type Error: 'x' is not a constructor

### ISSUE THREAD

**Issue by BobDeKort** [idehub/react-native-google-analytics-bridge#193] opened 2017-11-09 16:33 UTC
I have just implemented your great library and I am seeing the tracking events in my Google Analytics. But when I run my jest test it failes everywhere i have done:
`const GATracker = new GoogleAnalyticsTracker('XX-XXXXXXXXX-X');`
With the error: `TypeError: _reactNativeGoogleAnalyticsBridge.GoogleAnalyticsTracker is not a constructor`

I am importing like this: `import { GoogleAnalyticsTracker } from 'react-native-google-analytics-bridge';`

I'm using:
react-native 0.45.1, 
react-native-google-analytics-bridge 5.3.3

I have tried to find related issues but I have not found anything.
Let me know if you need any more information.

**Comment by cbrevik** [comment] 2017-11-10 14:29
Most likely duplicate of https://github.com/idehub/react-native-google-analytics-bridge/issues/189

You'll have to mock the library for testing.

**Closed by cbrevik** 2017-11-10 14:29 UTC

**Comment by BobDeKort** [comment] 2017-11-13 09:23
Hey @cbrevik thanks for the response but I'm already mocking the library in my tests.
Is there a specific function I need to mock or something, I'm not really familiar with jest testing.

Thanks!

**Comment by cbrevik** [comment] 2017-11-13 09:26
Hi @BobDeKort, if you're mocking the library in tests, then this error shouldn't occur at all. You are probably importing and using it somewhere, and the mock is not resolved.

**Comment by BobDeKort** [comment] 2017-11-14 13:42
@cbrevik Hey, I have tried learning how to mock libraries but I can't seem to find anything wrong with the code. 
Do you by any chance have any experience mocking this library using jest? And would you be willing to help me?
Thanks!
