### ISSUE TITLE
[QUESTION] Campaign Measurement on Android

### ISSUE THREAD

**Issue by xavierlefevre** [idehub/react-native-google-analytics-bridge#49] opened 2016-07-21 08:32 UTC
Hello,

I saw that you added the possibility to allow IDFA, and thus track campaign installs on iOS. I will push it to the company I work with for them to try it on.
However, can you confirm me that it won't work for Android ?
According to Google documentation, a specific piece of code needs to be in the implementation for them to track campaigns:
https://developers.google.com/analytics/devguides/collection/android/v4/campaigns#google-play-campaigns

I bet that I can manually place this piece of code in my own AndroidManifest and it should work.

But I don't want to mess up and have your input.

Thanks for your help

**Comment by cbrevik** [comment] 2016-07-21 09:37
Hi @xavierlefevre,

This is a duplicate of #30. As I said in my reply there, I haven't tested out campaigns myself. But, as you say, I think you will only need to modify your own `AndroidManifest.xml` to have it work. 

CC @9mm, don't know if he got it to work like that?

**Comment by 9mm** [comment] 2016-07-21 17:13
I didn't end up changing my current setup, so I'm not sure!

**Comment by xavierlefevre** [comment] 2016-07-25 09:22
Thank you guys for the very fast answer.

Not sure I will have time on this project to set this up for them, but for next time I know.

**Comment by cbrevik** [comment] 2017-06-22 05:31
See https://github.com/idehub/react-native-google-analytics-bridge/issues/30#issuecomment-310279389. Closing this issue.

**Closed by cbrevik** 2017-06-22 05:31 UTC
Labels: question
