### ISSUE TITLE
iOS app crashes

### ISSUE THREAD

**Issue by gaykov** [idehub/react-native-google-analytics-bridge#23] opened 2016-03-20 17:27 UTC
Hello!

iOS app crashes with the following output:

```
2016-03-20 20:26:00.408 [info][tid:com.facebook.React.JavaScript][RCTJSCProfiler.m:63] JSC profiler is not supported.
2016-03-20 20:26:00.897[6470:369518] WARNING: GoogleAnalytics 3.15 void GAIUncaughtExceptionHandler(NSException *) (GAIUncaughtExceptionHandler.m:48): Uncaught exception: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
2016-03-20 20:26:05.909[6470:369518] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000107f50e65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010712bdeb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000107e538ce -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 318
	3   CoreFoundation                      0x0000000107e65c3b +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
	4   Schnaeppchenfuchs                   0x0000000106464bc2 -[RCTGoogleAnalyticsBridge constantsToExport] + 98
	5   Schnaeppchenfuchs                   0x00000001063b9e25 __23-[RCTModuleData config]_block_invoke + 53
	6   Schnaeppchenfuchs                   0x00000001063cb6ed __RCTExecuteOnMainThread_block_invoke + 29
	7   libdispatch.dylib                   0x000000010b4e849b _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x000000010b4d1c3c _dispatch_barrier_sync_f_slow_invoke + 284
	9   libdispatch.dylib                   0x000000010b4e849b _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x000000010b4d02af _dispatch_main_queue_callback_4CF + 1738
	11  CoreFoundation                      0x0000000107eb0d09 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	12  CoreFoundation                      0x0000000107e722c9 __CFRunLoopRun + 2073
	13  CoreFoundation                      0x0000000107e71828 CFRunLoopRunSpecific + 488
	14  GraphicsServices                    0x000000010d19bad2 GSEventRunModal + 161
	15  UIKit                               0x0000000109b18610 UIApplicationMain + 171
	16  Schnaeppchenfuchs                   0x000000010632bbaf main + 111
	17  libdyld.dylib                       0x000000010b51c92d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

**Comment by cbrevik** [comment] 2016-03-20 17:41
Hi @gaykov ! 

I need some more information in order to help you here:

1. Which version of this library are you using.
2. What calls are you making when the crash occurs? Can you share code?

**Comment by gaykov** [comment] 2016-03-20 17:44
@cbrevik thank you for the response!

I'm using 1.3.0 and error occurs right after importing the lib
```javasript
import GoogleAnalytics from 'react-native-google-analytics-bridge';
```

**Comment by gaykov** [comment] 2016-03-20 17:48
I changed my version to `1.2.0` and error gone. Now I see only

```
RROR: GoogleAnalytics 3.15 -[GAI trackerWithName:trackingId:] (GAI.m:155): Nil or empty name supplied. Cannot create tracker.
```

**Comment by cbrevik** [comment] 2016-03-20 17:53
Thank you! I am able to re-produce it after removing the `GAITrackingId` from Info.plist. 

Will try to find a fix for this.

**Comment by gaykov** [comment] 2016-03-20 17:54
Amazing, thank you!

**Comment by gaykov** [comment] 2016-03-20 18:05
@cbrevik anyway, it does'n work for me (no data in GA). Do I need to add any other config to make it work? I added library to my project, changed `GAITrackingId`, imported ilbrary in js file then I do `GoogleAnalytics.trackScreenView('Home');` and I don't see any data in my GA account. An I doing something wrong?

**Comment by cbrevik** [comment] 2016-03-20 18:09
@gaykov, I have just published a new patch ( `1.3.1`) to fix the crash at least.

The recommended procedure is calling `GoogleAnalytics.setTrackerId('YOUR-ID')` on app startup (before any other calls).

Other than that, the default dispatch interval is every 20 seconds. So it might not be real-time view unless you wait a bit. It's also possible to set this to 0 seconds with `GoogleAnalytics.setDispatchInterval(0)`, though for battery/network reasons I recommend keeping it at least up to 30 seconds.

**Comment by cbrevik** [comment] 2016-03-21 08:55
Did it work out for you @gaykov?

**Comment by gaykov** [comment] 2016-03-23 07:58
@cbrevik I can't get the latest version work so I used the previous one. I'll try to figure out the problem and let you know

**Comment by cbrevik** [comment] 2016-03-24 10:12
You cannot get v1.3.1 with the bugfix to work @gaykov ?

**Comment by gaykov** [comment] 2016-03-24 11:01
The bug was fixed but analytics doesn't work itself. It works if I simply switch to the older version, without changing the code (only change initialising with GA-id)

**Comment by cbrevik** [comment] 2016-03-25 08:15
Can you turn [on verbose logging](https://github.com/idehub/react-native-google-analytics-bridge#logging) and check the XCode output window to see if the library logs any calls with v1.3.1?

Also, you do set the trackerId (`GoogleAnalytics.setTrackerId('YOUR-ID')`) before making any calls right? If it is not set then the Chrome debug console window should give you an error.

**Comment by cbrevik** [comment] 2016-03-26 20:46
I've released a new version `1.3.2` fixing the points below, can you test it?

* I don't know if you're using the code from the `examples` folder. But the difference I see there between `1.2` and `1.3` is that `optOut` is called on `1.3`. This makes the dispatches fail (in the example).

* I also noticed that the tracker-instantiation of `1.3.1` was not thread-safe in native code for iOS, which it now should be. I don't think that should've made a difference because of how calls are queued in RN. But you never know.

**Comment by cbrevik** [comment] 2016-04-06 12:46
I am not able to reproduce any other problems with tracking. So I am closing this issue.

**Closed by cbrevik** 2016-04-06 12:46 UTC

**Comment by tiendv89** [comment] 2017-06-22 12:49
Hey does the tracker work on iOS?
I got the error.
> ERROR: GoogleAnalytics 3.15 -[GAI trackerWithName:trackingId:] (GAI.m:155): Nil or empty name supplied. Cannot create tracker.

I found that you call `id<GAITracker> tracker = [[GAI sharedInstance] trackerWithTrackingId:trackerId];` at the start of every function, but the trackerId is null.

**Comment by cbrevik** [comment] 2017-06-22 13:35
@tiendv89 the tracker has changed over time, so I don't know if your problem is related to this issue.

Remember to send in trackerId when instantiating the tracker:
`let tracker = new GoogleAnalyticsTracker('UA-12345-1');`

See readme for more info: https://github.com/idehub/react-native-google-analytics-bridge#googleanalyticstracker-api

**Comment by tiendv89** [comment] 2017-06-23 02:05
I already added it to my code and it was initialized correctly in `init` funciton. However, the value is set to `staticTrackerId` only, which is not used anywhere after that.

**Comment by cbrevik** [comment] 2017-06-23 05:39
I'm not sure if we're talking about the same thing. 

The `init` (in objective-C) function uses the `staticTrackerId` which it exports as a constant to the JS side. This is in order to be backwards compatible with the old way of using this library where you set the trackerId in the Info.plist file.

Now though, the `trackerId` is sent in with every call, because it is saved inside the `GoogleAnalyticsTracker` on the JS side. So if you don't use the Info.plist (which I recommend not using), then you can ignore the `init` function and `staticTrackerId`.

Which version of this library are you using, and I need a code sample to understand how you're using it from JS?

**Comment by tiendv89** [comment] 2017-06-23 05:48
I am on `5.0.1`, and I did add `GA_Tracker = new GoogleAnalyticsTracker(config.GA_ID)` in my JS file.

**Comment by cbrevik** [comment] 2017-06-23 05:55
And you've debugged the `config.GA_ID` in JavaScript so you're 100% sure it is not null or empty?

**Comment by joncursi** [comment] 2017-10-04 13:24
@cbrevik I am also hitting this issue on iOS, but it only happens under very specific circumstances related to the following screen:

![screen shot 2017-10-04 at 9 21 11 am](https://user-images.githubusercontent.com/4974609/31178021-c1073dfa-a8e5-11e7-9d6f-ab75154fa7f7.png)

1. Enter text in the text input shown above
2. Tap the Twitter switch -> this *should* open up a Web view and ask the user to authorize sharing to twitter (using `react-native-oauth`)
3. The app crashes with:

```
2017-10-04 09:20:26.988850-0400 redbirdNative[21646:185333] *** Assertion failure in -[UIApplication _cachedSystemAnimationFenceCreatingIfNecessary:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3694.4.18/UIApplication.m:1706
2017-10-04 09:20:26.992844-0400 redbirdNative[21646:185333] WARNING: GoogleAnalytics 3.17 void GAIUncaughtExceptionHandler(NSException *) (GAIUncaughtExceptionHandler.m:48): Uncaught exception: accessing _cachedSystemAnimationFence requires the main thread
2017-10-04 09:20:27.578849-0400 redbirdNative[21646:184332] [] nw_connection_get_connected_socket 56 Connection has no connected handler
2017-10-04 09:20:27.579292-0400 redbirdNative[21646:184332] TCP Conn 0x600000176bc0 Failed : error 0:61 [61]
2017-10-04 09:20:29.611922-0400 redbirdNative[21646:185060] [] nw_connection_get_connected_socket 57 Connection has no connected handler
2017-10-04 09:20:29.612337-0400 redbirdNative[21646:185060] TCP Conn 0x60c00017d580 Failed : error 0:61 [61]
2017-10-04 09:20:31.641954-0400 redbirdNative[21646:185057] [] nw_connection_get_connected_socket 58 Connection has no connected handler
2017-10-04 09:20:31.642391-0400 redbirdNative[21646:185057] TCP Conn 0x60c00017d100 Failed : error 0:61 [61]
2017-10-04 09:20:31.993948-0400 redbirdNative[21646:185333] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'accessing _cachedSystemAnimationFence requires the main thread'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010bf6d1cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010a694f41 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010bf72362 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010a139089 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   UIKit                               0x000000010f4320dd -[UIApplication _cachedSystemAnimationFenceCreatingIfNecessary:] + 359
	5   UIKit                               0x000000010f4bc011 +[UIWindow _synchronizeDrawingWithPreCommitHandler:] + 57
	6   UIKit                               0x000000010fc2447f -[UIInputViewAnimationStyle launchAnimation:afterStarted:completion:forHost:fromCurrentPosition:] + 99
	7   UIKit                               0x0000000110073f81 -[UIInputWindowController moveFromPlacement:toPlacement:starting:completion:] + 1558
	8   UIKit                               0x000000011007c7b0 __43-[UIInputWindowController setInputViewSet:]_block_invoke.1477 + 97
	9   UIKit                               0x000000011006d2c8 -[UIInputWindowController performOperations:withTemplateNotificationInfo:] + 46
	10  UIKit                               0x000000011007c33c -[UIInputWindowController setInputViewSet:] + 1336
	11  UIKit                               0x00000001100735c2 -[UIInputWindowController performOperations:withAnimationStyle:] + 50
	12  UIKit                               0x000000010fc1cae4 -[UIPeripheralHost(UIKitInternal) setInputViews:animationStyle:] + 1147
	13  UIKit                               0x000000010fc1dd84 -[UIPeripheralHost(UIKitInternal) _preserveInputViewsWithId:animated:reset:] + 498
	14  UIKit                               0x000000010f5ea91e -[UIViewController _presentViewController:modalSourceViewController:presentationController:animationController:interactionController:completion:] + 1119
	15  UIKit                               0x000000010f5ec6ab -[UIViewController _presentViewController:withAnimationController:completion:] + 4621
	16  UIKit                               0x000000010f5ef1c1 __63-[UIViewController _presentViewController:animated:completion:]_block_invoke + 99
	17  UIKit                               0x000000010f5ef891 -[UIViewController _performCoordinatedPresentOrDismiss:animated:] + 532
	18  UIKit                               0x000000010f5ef120 -[UIViewController _presentViewController:animated:completion:] + 181
	19  UIKit                               0x000000010f5ef47f -[UIViewController presentViewController:animated:completion:] + 159
	20  redbirdNative                       0x00000001089c20d9 __34+[OAuthManager setupOAuthHandler:]_block_invoke + 281
	21  DCTAuth                             0x00000001097f05cc -[DCTAuthPlatform openURL:completion:] + 252
	22  DCTAuth                             0x00000001097f6555 -[DCTAuthURLOpenerOperation start] + 181
	23  Foundation                          0x000000010a0a5cff __NSOQSchedule_f + 369
	24  libdispatch.dylib                   0x0000000111c8b43c _dispatch_client_callout + 8
	25  libdispatch.dylib                   0x0000000111c91856 _dispatch_continuation_pop + 967
	26  libdispatch.dylib                   0x0000000111c8fc86 _dispatch_async_redirect_invoke + 780
	27  libdispatch.dylib                   0x0000000111c971f9 _dispatch_root_queue_drain + 772
	28  libdispatch.dylib                   0x0000000111c96e97 _dispatch_worker_thread3 + 132
	29  libsystem_pthread.dylib             0x000000011214e5a2 _pthread_wqthread + 1299
	30  libsystem_pthread.dylib             0x000000011214e07d start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

I can confirm that I have set up the library properly from the README. I am on the latest version.

NOTE: Here's the weird thing. If you do the same steps above WITHOUT entering any text into the text field, the WebView opens properly. But it's this text laying in the text field that causes the cache / crash issue.

**Comment by joncursi** [comment] 2017-10-04 13:37
Update: my iOS crash seemed to be caused by the [OAuth package itself](https://github.com/fullstackreact/react-native-oauth/pull/150), not this library. Sorry for the false positive!
