### ISSUE TITLE
Compatibility with jest

### ISSUE THREAD

**Issue by ajagesser** [idehub/react-native-google-analytics-bridge#62] opened 2016-08-22 18:02 UTC
I get this error 

retrieveAuthor › it calls retrieveAuthor method with the correct params
- TypeError: Cannot read property 'nativeTrackerId' of undefined
      at Object.<anonymous> (node_modules/react-native-google-analytics-bridge/index.js:6:37)
      at Object.<anonymous> (src/requests/Request.js:38:63)
      at Object._callee$ (__tests__/AuthorRequest-test.js:11:10)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)

I'll quick fix (in my app code) this by using require instead of import for now.

**Comment by cbrevik** [comment] 2016-08-23 06:13
Might this be related to #59?

**Comment by vitorebatista** [comment] 2016-10-19 13:23
I have the same problem when I use **Jest**

**Comment by jaimecorrea** [comment] 2016-10-31 20:22
Same issue in Android... any news?

**Comment by cbrevik** [comment] 2016-11-01 05:36
Regardless of compatibility with Jest or not, there's an open PR that reworks the logic of handling trackerId, so we'll have to look at this again after that is merged.

**Comment by cjpwrs** [comment] 2016-11-02 21:26
We were able to get around this by mocking  react-native-google-analytics-bridge. This is what we used:
`export default {
  trackScreenView() {},
  trackEvent() {},
};`

**Comment by skylarmb** [comment] 2016-11-04 18:51
Same issue. For anyone else who is new to Jest / mocks, create a folder called `__mocks__` in the same directory as `node_modules` if you don't already have one. In `__mocks__` create `react-native-google-analytics-bridge.js`. Here is mine... You probably don't need to stub out all of these but why not.


```
export default {
  trackScreenView() {},
  trackEvent() {},
  setUser() {},
  setTrackerId() {}
};```

**Comment by antonfisher** [comment] 2016-11-06 09:13
The same issue while running on android emulator for me.
Was fixed by replacing this string in `index.js`:
```javascript
// old version
export default new GoogleAnalyticsBackwardsCompability(GoogleAnalyticsBridge.nativeTrackerId);
```
to this one:
```javascript
// new version
const id = (GoogleAnalyticsBridge ? GoogleAnalyticsBridge.nativeTrackerId : '');
export default new GoogleAnalyticsBackwardsCompability(id);
```
Commit: https://github.com/antonfisher/react-native-google-analytics-bridge/commit/6c27a8614cac1f1b36aa022c487abddbad077388

P.S. Thank you for this library!

**Comment by cbrevik** [comment] 2016-11-06 09:18
@antonfisher That's while using Jest?

In `v4.0.0` released yesterday, the tracker should be constructed instead of used statically:
`let tracker = new GoogleAnalyticsTracker('UA-12345-1');`. So use of `nativeTrackerId` and `setTrackerId` has been deprecated.

I think if you changed your code to instead to use the new `GoogleAnalyticsTracker` class, it might stop this from occurring.

**Comment by antonfisher** [comment] 2016-11-07 06:44
@cbrevik I do not use Jest. It has happened with the latest 4.0.0 version from npm. My code:
```javascript
import {GoogleAnalyticsTracker} from 'react-native-google-analytics-bridge'
...
this.ga = new GoogleAnalyticsTracker(gaNumber) // fired an error here
```
This has happened only on android emulator (release version works properly on device):
![image](https://cloud.githubusercontent.com/assets/599352/20047651/28e100da-a46b-11e6-99d0-c7bda10569c1.png)

**Solution**
During preparing an explanation, I have updated all android packages (mine were ~3 weeks outdated) and it helped! Everything is good now!

Thank you!

**Comment by ayercm** [comment] 2016-11-18 01:22
I can't get it to work... I have upgraded to 4.0.1 and changed my code per the readme.md

import GoogleAnalyticsTracker from 'react-native-google-analytics-bridge';
let tracker1 = new GoogleAnalyticsTracker('XXXXXXXXXX');
tracker1.trackScreenView('Beacon Screen');

Inside jest I include the file that uses the GoogleAnalyticsTracker, but when I run it I too get...

Test suite failed to run

    TypeError: Cannot read property 'nativeTrackerId' of undefined
      
      at Object.<anonymous> (node_modules/react-native-google-analytics-bridge/index.js:18:114)
      at Object.<anonymous> (src/modules/beacons/BeaconView.js:8:39)

/**
 * Backwards compatibility default export.
 * Versions bellow 3.1.0 used static GoogleAnalytics class.
 * This exported instance makes sure older implementations work.
 */
export default new GoogleAnalyticsBackwardsCompability(GoogleAnalyticsBridge.nativeTrackerId);

I tried mocking out the functions, but that didn't work either. I must be missing something.

**Comment by cbrevik** [comment] 2016-11-18 05:56
Hi @ayercm,

Change your import `import GoogleAnalyticsTracker from 'react-native-google-analytics-bridge';` to `import { GoogleAnalyticsTracker } from 'react-native-google-analytics-bridge'`. 

That is the backwards-compatible class you're importing.

I am closing this issue since it is a duplicate of #73.

**Closed by cbrevik** 2016-11-18 05:56 UTC
